language: c

before_script:
- sudo apt-get update -qq
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo apt-key add -
- echo "deb http://packages.wazuh.com.s3-website-us-west-1.amazonaws.com/3.x/apt/ unstable main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -q
- sudo apt-get -y install wazuh-api

script:
- curl foo:bar@localhost:55000


